enum LauncherSettingsKey {
    static let autoConnectCore = "Settings.AutoConnectCore"
    static let autoCheckUpdates = "Settings.AutoCheckUpdates"
    static let closeWindowBehavior = "Settings.CloseWindowBehavior"
    static let defaultGameDirectory = "Settings.DefaultGameDirectory"
    static let windowWidth = "Settings.WindowWidth"
    static let windowHeight = "Settings.WindowHeight"
    static let jvmArguments = "Settings.JVMArguments"
    static let memoryPolicy = "Settings.MemoryPolicy"
    static let jvmProfile = "Settings.JVMProfile"
    static let graphicsProfile = "Settings.GraphicsProfile"
    static let performanceApplyMode = "Settings.PerformanceApplyMode"
    static let performanceLocalTelemetryEnabled = "Settings.PerformanceLocalTelemetryEnabled"
    static let performanceExperimentsEnabled = "Settings.PerformanceExperimentsEnabled"
    static let performanceShareAnonymousPriors = "Settings.PerformanceShareAnonymousPriors"
    static let installMissingFilesBeforeLaunch = "Settings.InstallMissingFilesBeforeLaunch"
    static let autoDetectJava = "Settings.AutoDetectJava"
    static let downloadStrategy = "Settings.DownloadStrategy"
    static let downloadConcurrency = "Settings.DownloadConcurrency"
    static let downloadRetryCount = "Settings.DownloadRetryCount"
    static let proxyAddress = "Settings.ProxyAddress"
    static let downloadSource = "Settings.DownloadSource"
    static let autoSaveLogs = "Settings.AutoSaveLogs"
    static let logRetentionDays = "Settings.LogRetentionDays"
    static let advancedModeEnabled = "Settings.AdvancedModeEnabled"
}
