extension AppText {
    var english: String {
        switch self {
        case .launch: return "Launch"
        case .instances: return "Local Instances"
        case .versions: return "Versions"
        case .account: return "Account"
        case .tasks: return "Tasks"
        case .logs: return "Logs"
        case .appearance: return "Appearance"
        case .settings: return "Settings"
        case .launchSubtitle: return "Current local instance launch center with checks, resources and task feedback."
        case .instancesSubtitle: return "Manage Minecraft instances already installed on disk."
        case .versionsSubtitle: return "Inspect versions, loaders, mods, resource packs and shaders."
        case .accountSubtitle: return "Manage Microsoft sign-in for launch sessions."
        case .tasksSubtitle: return "Track install, launch and download tasks."
        case .logsSubtitle: return "Inspect local launcher and Core output."
        case .appearanceSubtitle: return "Tune theme, material and background settings."
        case .settingsSubtitle: return "Configure launcher behavior, Java, Minecraft, downloads and diagnostics."
        case .startCore: return "Start Core"
        case .stopCore: return "Stop Core"
        case .language: return "Language"
        case .mode: return "Mode"
        case .accent: return "Accent"
        case .preset: return "Preset"
        case .apply: return "Apply"
        case .glass: return "Glass"
        case .background: return "Background"
        case .choose: return "Choose"
        case .softTexture: return "Soft Texture"
        case .enabled: return "Enabled"
        case .density: return "Density"
        case .versionSelector: return "Version Selector"
        case .channel: return "Channel"
        case .loaderPlan: return "Loader Plan"
        case .loader: return "Loader"
        case .loaderPlanDescription: return "Fabric, Quilt, Forge, and NeoForge are tracked here as planned loader targets. Install integration can be wired to the downloader in a later phase."
        case .contentManager: return "Content Manager"
        case .refresh: return "Refresh"
        case .openFolder: return "Open Folder"
        case .type: return "Type"
        case .noItems: return "No %@"
        case .deleteSelectedFile: return "Delete selected file?"
        case .deleteFile: return "Delete File"
        case .cancel: return "Cancel"
        case .released: return "Released"
        case .java: return "Java"
        case .download: return "Download"
        case .verify: return "Verify"
        case .enable: return "Enable"
        case .disable: return "Disable"
        case .delete: return "Delete"
        case .status: return "Status"
        case .details: return "Details"
        case .instanceDetails: return "Game Configuration Details"
        case .readyForTasks: return "Ready for tasks"
        case .coreLogs: return "Core Logs"
        case .export: return "Export"
        case .clear: return "Clear"
        case .microsoftAccount: return "Microsoft Account"
        case .signedIn: return "Signed In"
        case .restoring: return "Restoring"
        case .waiting: return "Waiting"
        case .error: return "Error"
        case .signedOut: return "Signed Out"
        case .ready: return "Ready"
        case .attention: return "Attention"
        case .failed: return "Failed"
        case .downloading: return "Downloading"
        case .running: return "Running"
        case .idle: return "Idle"
        case .openMicrosoft: return "Open Microsoft"
        }
    }

    var chineseSimplified: String {
        switch self {
        case .launch: return "启动"
        case .instances: return "本地实例"
        case .versions: return "版本"
        case .account: return "账号"
        case .tasks: return "任务"
        case .logs: return "日志"
        case .appearance: return "外观"
        case .settings: return "设置"
        case .launchSubtitle: return "当前本地实例启动中心，包含检查、资源与任务反馈。"
        case .instancesSubtitle: return "管理已经安装到本地磁盘的 Minecraft 实例。"
        case .versionsSubtitle: return "查看版本、加载器、Mod、资源包和光影包。"
        case .accountSubtitle: return "管理用于启动游戏的 Microsoft 登录。"
        case .tasksSubtitle: return "跟踪安装、启动和下载任务。"
        case .logsSubtitle: return "查看启动器和 Core 输出。"
        case .appearanceSubtitle: return "调整主题、材质和背景设置。"
        case .settingsSubtitle: return "配置启动器行为、Java、Minecraft、下载和诊断。"
        case .startCore: return "启动 Core"
        case .stopCore: return "停止 Core"
        case .language: return "语言"
        case .mode: return "模式"
        case .accent: return "强调色"
        case .preset: return "预设"
        case .apply: return "应用"
        case .glass: return "玻璃"
        case .background: return "背景"
        case .choose: return "选择"
        case .softTexture: return "柔和纹理"
        case .enabled: return "启用"
        case .density: return "密度"
        case .versionSelector: return "版本选择器"
        case .channel: return "通道"
        case .loaderPlan: return "加载器规划"
        case .loader: return "加载器"
        case .loaderPlanDescription: return "Fabric、Quilt、Forge 和 NeoForge 会作为规划中的加载器目标展示，后续可接入下载器安装流程。"
        case .contentManager: return "内容管理"
        case .refresh: return "刷新"
        case .openFolder: return "打开文件夹"
        case .type: return "类型"
        case .noItems: return "没有%@"
        case .deleteSelectedFile: return "删除选中的文件？"
        case .deleteFile: return "删除文件"
        case .cancel: return "取消"
        case .released: return "发布时间"
        case .java: return "Java"
        case .download: return "下载"
        case .verify: return "校验"
        case .enable: return "启用"
        case .disable: return "禁用"
        case .delete: return "删除"
        case .status: return "状态"
        case .details: return "详情"
        case .instanceDetails: return "游戏配置详情"
        case .readyForTasks: return "任务就绪"
        case .coreLogs: return "Core 日志"
        case .export: return "导出"
        case .clear: return "清空"
        case .microsoftAccount: return "Microsoft 账号"
        case .signedIn: return "已登录"
        case .restoring: return "正在恢复"
        case .waiting: return "等待中"
        case .error: return "错误"
        case .signedOut: return "未登录"
        case .ready: return "就绪"
        case .attention: return "注意"
        case .failed: return "失败"
        case .downloading: return "下载中"
        case .running: return "运行中"
        case .idle: return "空闲"
        case .openMicrosoft: return "打开 Microsoft"
        }
    }
}
