extension AppText {
    var spanish: String {
        switch self {
        case .launch: return "Iniciar"
        case .instances: return "Instancias locales"
        case .versions: return "Versiones"
        case .account: return "Cuenta"
        case .tasks: return "Tareas"
        case .logs: return "Registros"
        case .appearance: return "Apariencia"
        case .settings: return "Ajustes"
        case .launchSubtitle: return "Centro de inicio de la instancia local con comprobaciones, recursos y tareas."
        case .instancesSubtitle: return "Gestiona las instancias de Minecraft ya instaladas en el disco."
        case .versionsSubtitle: return "Revisa versiones, loaders, mods, recursos y shaders."
        case .accountSubtitle: return "Gestiona el inicio de sesión de Microsoft."
        case .tasksSubtitle: return "Supervisa instalaciones, inicios y descargas."
        case .logsSubtitle: return "Revisa la salida del launcher y del Core."
        case .appearanceSubtitle: return "Ajusta el tema, los materiales y el fondo."
        case .settingsSubtitle: return "Configura launcher, Java, Minecraft, descargas y diagnóstico."
        case .startCore: return "Iniciar Core"
        case .stopCore: return "Detener Core"
        case .language: return "Idioma"
        case .mode: return "Modo"
        case .accent: return "Acento"
        case .preset: return "Preajuste"
        case .apply: return "Aplicar"
        case .glass: return "Cristal"
        case .background: return "Fondo"
        case .choose: return "Elegir"
        case .softTexture: return "Textura suave"
        case .enabled: return "Activado"
        case .density: return "Densidad"
        case .versionSelector: return "Selector de versión"
        case .channel: return "Canal"
        case .loaderPlan: return "Plan de loaders"
        case .loader: return "Loader"
        case .loaderPlanDescription: return "Fabric, Quilt, Forge y NeoForge se registran como loaders previstos. La instalación podrá conectarse al descargador."
        case .contentManager: return "Gestor de contenido"
        case .refresh: return "Actualizar"
        case .openFolder: return "Abrir carpeta"
        case .type: return "Tipo"
        case .noItems: return "Sin %@"
        case .deleteSelectedFile: return "¿Eliminar el archivo seleccionado?"
        case .deleteFile: return "Eliminar archivo"
        case .cancel: return "Cancelar"
        case .released: return "Publicado"
        case .java: return "Java"
        case .download: return "Descarga"
        case .verify: return "Verificar"
        case .enable: return "Activar"
        case .disable: return "Desactivar"
        case .delete: return "Eliminar"
        case .status: return "Estado"
        case .details: return "Detalles"
        case .instanceDetails: return "Detalles de configuración"
        case .readyForTasks: return "Listo para tareas"
        case .coreLogs: return "Registros Core"
        case .export: return "Exportar"
        case .clear: return "Limpiar"
        case .microsoftAccount: return "Cuenta Microsoft"
        case .signedIn: return "Conectado"
        case .restoring: return "Restaurando"
        case .waiting: return "Esperando"
        case .error: return "Error"
        case .signedOut: return "Desconectado"
        case .ready: return "Listo"
        case .attention: return "Atención"
        case .failed: return "Fallido"
        case .downloading: return "Descargando"
        case .running: return "En ejecución"
        case .idle: return "Inactivo"
        case .openMicrosoft: return "Abrir Microsoft"
        }
    }
}
