extension AppText {
    var italian: String {
        switch self {
        case .launch: return "Avvio"
        case .instances: return "Istanze locali"
        case .versions: return "Versioni"
        case .account: return "Account"
        case .tasks: return "Attività"
        case .logs: return "Log"
        case .appearance: return "Aspetto"
        case .settings: return "Impostazioni"
        case .launchSubtitle: return "Centro avvio dell'istanza locale con controlli, risorse e attività."
        case .instancesSubtitle: return "Gestisci le istanze Minecraft già installate sul disco."
        case .versionsSubtitle: return "Controlla versioni, loader, mod, resource pack e shader."
        case .accountSubtitle: return "Gestisci l'accesso Microsoft per le sessioni di avvio."
        case .tasksSubtitle: return "Monitora installazioni, avvii e download."
        case .logsSubtitle: return "Controlla l'output del launcher e del Core."
        case .appearanceSubtitle: return "Regola tema, materiali e sfondo."
        case .settingsSubtitle: return "Configura launcher, Java, Minecraft, download e diagnostica."
        case .startCore: return "Avvia Core"
        case .stopCore: return "Ferma Core"
        case .language: return "Lingua"
        case .mode: return "Modalità"
        case .accent: return "Accento"
        case .preset: return "Preset"
        case .apply: return "Applica"
        case .glass: return "Vetro"
        case .background: return "Sfondo"
        case .choose: return "Scegli"
        case .softTexture: return "Texture morbida"
        case .enabled: return "Attiva"
        case .density: return "Densità"
        case .versionSelector: return "Selettore versione"
        case .channel: return "Canale"
        case .loaderPlan: return "Piano loader"
        case .loader: return "Loader"
        case .loaderPlanDescription: return "Fabric, Quilt, Forge e NeoForge sono tracciati come loader pianificati. L'installazione potrà essere collegata al downloader."
        case .contentManager: return "Gestione contenuti"
        case .refresh: return "Aggiorna"
        case .openFolder: return "Apri cartella"
        case .type: return "Tipo"
        case .noItems: return "Nessun %@"
        case .deleteSelectedFile: return "Eliminare il file selezionato?"
        case .deleteFile: return "Elimina file"
        case .cancel: return "Annulla"
        case .released: return "Rilasciato"
        case .java: return "Java"
        case .download: return "Download"
        case .verify: return "Verifica"
        case .enable: return "Attiva"
        case .disable: return "Disattiva"
        case .delete: return "Elimina"
        case .status: return "Stato"
        case .details: return "Dettagli"
        case .instanceDetails: return "Dettagli configurazione"
        case .readyForTasks: return "Pronto per le attività"
        case .coreLogs: return "Log Core"
        case .export: return "Esporta"
        case .clear: return "Pulisci"
        case .microsoftAccount: return "Account Microsoft"
        case .signedIn: return "Connesso"
        case .restoring: return "Ripristino"
        case .waiting: return "In attesa"
        case .error: return "Errore"
        case .signedOut: return "Disconnesso"
        case .ready: return "Pronto"
        case .attention: return "Attenzione"
        case .failed: return "Fallito"
        case .downloading: return "Download"
        case .running: return "In esecuzione"
        case .idle: return "Inattivo"
        case .openMicrosoft: return "Apri Microsoft"
        }
    }

    var french: String {
        switch self {
        case .launch: return "Lancer"
        case .instances: return "Instances locales"
        case .versions: return "Versions"
        case .account: return "Compte"
        case .tasks: return "Tâches"
        case .logs: return "Journaux"
        case .appearance: return "Apparence"
        case .settings: return "Réglages"
        case .launchSubtitle: return "Centre de lancement de l'instance locale avec vérifications, ressources et tâches."
        case .instancesSubtitle: return "Gérez les instances Minecraft déjà installées sur le disque."
        case .versionsSubtitle: return "Consultez versions, chargeurs, mods, packs et shaders."
        case .accountSubtitle: return "Gérez la connexion Microsoft pour les sessions de lancement."
        case .tasksSubtitle: return "Suivez les installations, lancements et téléchargements."
        case .logsSubtitle: return "Inspectez la sortie du lanceur et du Core."
        case .appearanceSubtitle: return "Ajustez le thème, les matériaux et l'arrière-plan."
        case .settingsSubtitle: return "Configurez lanceur, Java, Minecraft, téléchargements et diagnostics."
        case .startCore: return "Démarrer Core"
        case .stopCore: return "Arrêter Core"
        case .language: return "Langue"
        case .mode: return "Mode"
        case .accent: return "Accent"
        case .preset: return "Préréglage"
        case .apply: return "Appliquer"
        case .glass: return "Verre"
        case .background: return "Arrière-plan"
        case .choose: return "Choisir"
        case .softTexture: return "Texture douce"
        case .enabled: return "Activé"
        case .density: return "Densité"
        case .versionSelector: return "Sélecteur de version"
        case .channel: return "Canal"
        case .loaderPlan: return "Plan des chargeurs"
        case .loader: return "Chargeur"
        case .loaderPlanDescription: return "Fabric, Quilt, Forge et NeoForge sont suivis comme chargeurs prévus. L'installation pourra être reliée au téléchargeur."
        case .contentManager: return "Gestion du contenu"
        case .refresh: return "Actualiser"
        case .openFolder: return "Ouvrir le dossier"
        case .type: return "Type"
        case .noItems: return "Aucun %@"
        case .deleteSelectedFile: return "Supprimer le fichier sélectionné ?"
        case .deleteFile: return "Supprimer le fichier"
        case .cancel: return "Annuler"
        case .released: return "Sortie"
        case .java: return "Java"
        case .download: return "Téléchargement"
        case .verify: return "Vérification"
        case .enable: return "Activer"
        case .disable: return "Désactiver"
        case .delete: return "Supprimer"
        case .status: return "État"
        case .details: return "Détails"
        case .instanceDetails: return "Détails de la configuration"
        case .readyForTasks: return "Prêt pour les tâches"
        case .coreLogs: return "Journaux Core"
        case .export: return "Exporter"
        case .clear: return "Effacer"
        case .microsoftAccount: return "Compte Microsoft"
        case .signedIn: return "Connecté"
        case .restoring: return "Restauration"
        case .waiting: return "En attente"
        case .error: return "Erreur"
        case .signedOut: return "Déconnecté"
        case .ready: return "Prêt"
        case .attention: return "Attention"
        case .failed: return "Échec"
        case .downloading: return "Téléchargement"
        case .running: return "En cours"
        case .idle: return "Inactif"
        case .openMicrosoft: return "Ouvrir Microsoft"
        }
    }

    var spanish: String {
        switch self {
        case .launch: return "Iniciar"
        case .instances: return "Instancias locales"
        case .versions: return "Versiones"
        case .account: return "Cuenta"
        case .tasks: return "Tareas"
        case .logs: return "Registros"
        case .appearance: return "Apariencia"
        case .settings: return "Ajustes"
        case .launchSubtitle: return "Centro de inicio de la instancia local con comprobaciones, recursos y tareas."
        case .instancesSubtitle: return "Gestiona las instancias de Minecraft ya instaladas en el disco."
        case .versionsSubtitle: return "Revisa versiones, loaders, mods, recursos y shaders."
        case .accountSubtitle: return "Gestiona el inicio de sesión de Microsoft."
        case .tasksSubtitle: return "Supervisa instalaciones, inicios y descargas."
        case .logsSubtitle: return "Revisa la salida del launcher y del Core."
        case .appearanceSubtitle: return "Ajusta el tema, los materiales y el fondo."
        case .settingsSubtitle: return "Configura launcher, Java, Minecraft, descargas y diagnóstico."
        case .startCore: return "Iniciar Core"
        case .stopCore: return "Detener Core"
        case .language: return "Idioma"
        case .mode: return "Modo"
        case .accent: return "Acento"
        case .preset: return "Preajuste"
        case .apply: return "Aplicar"
        case .glass: return "Cristal"
        case .background: return "Fondo"
        case .choose: return "Elegir"
        case .softTexture: return "Textura suave"
        case .enabled: return "Activado"
        case .density: return "Densidad"
        case .versionSelector: return "Selector de versión"
        case .channel: return "Canal"
        case .loaderPlan: return "Plan de loaders"
        case .loader: return "Loader"
        case .loaderPlanDescription: return "Fabric, Quilt, Forge y NeoForge se registran como loaders previstos. La instalación podrá conectarse al descargador."
        case .contentManager: return "Gestor de contenido"
        case .refresh: return "Actualizar"
        case .openFolder: return "Abrir carpeta"
        case .type: return "Tipo"
        case .noItems: return "Sin %@"
        case .deleteSelectedFile: return "¿Eliminar el archivo seleccionado?"
        case .deleteFile: return "Eliminar archivo"
        case .cancel: return "Cancelar"
        case .released: return "Publicado"
        case .java: return "Java"
        case .download: return "Descarga"
        case .verify: return "Verificar"
        case .enable: return "Activar"
        case .disable: return "Desactivar"
        case .delete: return "Eliminar"
        case .status: return "Estado"
        case .details: return "Detalles"
        case .instanceDetails: return "Detalles de configuración"
        case .readyForTasks: return "Listo para tareas"
        case .coreLogs: return "Registros Core"
        case .export: return "Exportar"
        case .clear: return "Limpiar"
        case .microsoftAccount: return "Cuenta Microsoft"
        case .signedIn: return "Conectado"
        case .restoring: return "Restaurando"
        case .waiting: return "Esperando"
        case .error: return "Error"
        case .signedOut: return "Desconectado"
        case .ready: return "Listo"
        case .attention: return "Atención"
        case .failed: return "Fallido"
        case .downloading: return "Descargando"
        case .running: return "En ejecución"
        case .idle: return "Inactivo"
        case .openMicrosoft: return "Abrir Microsoft"
        }
    }
}
