extension AppText {
    var italian: String {
        switch self {
        case .launch: return "Avvio"
        case .instances: return "Istanze locali"
        case .versions: return "Versioni"
        case .account: return "Account"
        case .tasks: return "Attività"
        case .logs: return "Log"
        case .appearance: return "Aspetto"
        case .settings: return "Impostazioni"
        case .launchSubtitle: return "Centro avvio dell'istanza locale con controlli, risorse e attività."
        case .instancesSubtitle: return "Gestisci le istanze Minecraft già installate sul disco."
        case .versionsSubtitle: return "Controlla versioni, loader, mod, resource pack e shader."
        case .accountSubtitle: return "Gestisci l'accesso Microsoft per le sessioni di avvio."
        case .tasksSubtitle: return "Monitora installazioni, avvii e download."
        case .logsSubtitle: return "Controlla l'output del launcher e del Core."
        case .appearanceSubtitle: return "Regola tema, materiali e sfondo."
        case .settingsSubtitle: return "Configura launcher, Java, Minecraft, download e diagnostica."
        case .startCore: return "Avvia Core"
        case .stopCore: return "Ferma Core"
        case .language: return "Lingua"
        case .mode: return "Modalità"
        case .accent: return "Accento"
        case .preset: return "Preset"
        case .apply: return "Applica"
        case .glass: return "Vetro"
        case .background: return "Sfondo"
        case .choose: return "Scegli"
        case .softTexture: return "Texture morbida"
        case .enabled: return "Attiva"
        case .density: return "Densità"
        case .versionSelector: return "Selettore versione"
        case .channel: return "Canale"
        case .loaderPlan: return "Piano loader"
        case .loader: return "Loader"
        case .loaderPlanDescription: return "Fabric, Quilt, Forge e NeoForge sono tracciati come loader pianificati. L'installazione potrà essere collegata al downloader."
        case .contentManager: return "Gestione contenuti"
        case .refresh: return "Aggiorna"
        case .openFolder: return "Apri cartella"
        case .type: return "Tipo"
        case .noItems: return "Nessun %@"
        case .deleteSelectedFile: return "Eliminare il file selezionato?"
        case .deleteFile: return "Elimina file"
        case .cancel: return "Annulla"
        case .released: return "Rilasciato"
        case .java: return "Java"
        case .download: return "Download"
        case .verify: return "Verifica"
        case .enable: return "Attiva"
        case .disable: return "Disattiva"
        case .delete: return "Elimina"
        case .status: return "Stato"
        case .details: return "Dettagli"
        case .instanceDetails: return "Dettagli configurazione"
        case .readyForTasks: return "Pronto per le attività"
        case .coreLogs: return "Log Core"
        case .export: return "Esporta"
        case .clear: return "Pulisci"
        case .microsoftAccount: return "Account Microsoft"
        case .signedIn: return "Connesso"
        case .restoring: return "Ripristino"
        case .waiting: return "In attesa"
        case .error: return "Errore"
        case .signedOut: return "Disconnesso"
        case .ready: return "Pronto"
        case .attention: return "Attenzione"
        case .failed: return "Fallito"
        case .downloading: return "Download"
        case .running: return "In esecuzione"
        case .idle: return "Inattivo"
        case .openMicrosoft: return "Apri Microsoft"
        }
    }
}
