extension AppText {
    var french: String {
        switch self {
        case .launch: return "Lancer"
        case .instances: return "Instances locales"
        case .versions: return "Versions"
        case .account: return "Compte"
        case .tasks: return "Tâches"
        case .logs: return "Journaux"
        case .appearance: return "Apparence"
        case .settings: return "Réglages"
        case .launchSubtitle: return "Centre de lancement de l'instance locale avec vérifications, ressources et tâches."
        case .instancesSubtitle: return "Gérez les instances Minecraft déjà installées sur le disque."
        case .versionsSubtitle: return "Consultez versions, chargeurs, mods, packs et shaders."
        case .accountSubtitle: return "Gérez la connexion Microsoft pour les sessions de lancement."
        case .tasksSubtitle: return "Suivez les installations, lancements et téléchargements."
        case .logsSubtitle: return "Inspectez la sortie du lanceur et du Core."
        case .appearanceSubtitle: return "Ajustez le thème, les matériaux et l'arrière-plan."
        case .settingsSubtitle: return "Configurez lanceur, Java, Minecraft, téléchargements et diagnostics."
        case .startCore: return "Démarrer Core"
        case .stopCore: return "Arrêter Core"
        case .language: return "Langue"
        case .mode: return "Mode"
        case .accent: return "Accent"
        case .preset: return "Préréglage"
        case .apply: return "Appliquer"
        case .glass: return "Verre"
        case .background: return "Arrière-plan"
        case .choose: return "Choisir"
        case .softTexture: return "Texture douce"
        case .enabled: return "Activé"
        case .density: return "Densité"
        case .versionSelector: return "Sélecteur de version"
        case .channel: return "Canal"
        case .loaderPlan: return "Plan des chargeurs"
        case .loader: return "Chargeur"
        case .loaderPlanDescription: return "Fabric, Quilt, Forge et NeoForge sont suivis comme chargeurs prévus. L'installation pourra être reliée au téléchargeur."
        case .contentManager: return "Gestion du contenu"
        case .refresh: return "Actualiser"
        case .openFolder: return "Ouvrir le dossier"
        case .type: return "Type"
        case .noItems: return "Aucun %@"
        case .deleteSelectedFile: return "Supprimer le fichier sélectionné ?"
        case .deleteFile: return "Supprimer le fichier"
        case .cancel: return "Annuler"
        case .released: return "Sortie"
        case .java: return "Java"
        case .download: return "Téléchargement"
        case .verify: return "Vérification"
        case .enable: return "Activer"
        case .disable: return "Désactiver"
        case .delete: return "Supprimer"
        case .status: return "État"
        case .details: return "Détails"
        case .instanceDetails: return "Détails de la configuration"
        case .readyForTasks: return "Prêt pour les tâches"
        case .coreLogs: return "Journaux Core"
        case .export: return "Exporter"
        case .clear: return "Effacer"
        case .microsoftAccount: return "Compte Microsoft"
        case .signedIn: return "Connecté"
        case .restoring: return "Restauration"
        case .waiting: return "En attente"
        case .error: return "Erreur"
        case .signedOut: return "Déconnecté"
        case .ready: return "Prêt"
        case .attention: return "Attention"
        case .failed: return "Échec"
        case .downloading: return "Téléchargement"
        case .running: return "En cours"
        case .idle: return "Inactif"
        case .openMicrosoft: return "Ouvrir Microsoft"
        }
    }
}
